### ISSUE TITLE
Support Angular CLI

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite-ecosystem-ci#4]
Downstream reproduction: https://github.com/justinogt/angular-blocksuite

Discord discussion: https://discord.com/channels/959027316334407691/1006208074316521573/1153666479116533791

Current bugs:
- Slash menu won't disappear after pressing / then enter.
- Need to press enter twice to insert a new line.
- CSS variables are all lost after optimizing in production mode.

**Comment by fourdim** [comment]
Working version: https://github.com/fourdim/angular-blocksuite

**Comment by doodlewind** [comment]
@fourdim awesome work! Would be great if you can move it here :D

**Comment by doodlewind** [comment]
Closed by #28
